font-family = Monaco
font-size = 14

copy-on-select = clipboard

shell-integration = detect
macos-option-as-alt = true
confirm-close-surface = false

window-save-state = never
window-inherit-working-directory = false
tab-inherit-working-directory = false
split-inherit-working-directory = false
