[General]
dns-server = system
ipv6 = false
ipv6-vif = disabled

[Proxy]
proxy = 

[Rule]
IP-CIDR,0.0.0.0/32,REJECT,no-resolve
PROTOCOL,QUIC,REJECT
DOMAIN-SUFFIX,github.com,proxy
DEST-PORT,22,DIRECT
RULE-SET,SYSTEM,DIRECT
DOMAIN-SET,https://cdn.jsdelivr.net/gh/geekdada/surge-list/domain-set/adaway.txt,REJECT
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/gfw.txt,proxy
DOMAIN-SET,https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/direct.txt,DIRECT
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT
FINAL,proxy,dns-failed
