[General]
dns-server = system
ipv6 = false
block-quic = all-proxy

[Proxy]
jp = 
jp-warp = 

[Proxy Group]
relay = select
ai = select

[Rule]
RULE-SET,SYSTEM,DIRECT
DEST-PORT,22,DIRECT
DOMAIN-SET,https://cdn.jsdelivr.net/gh/geekdada/surge-list/domain-set/adaway.txt,REJECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GitHub/GitHub.list,relay
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list,ai
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Claude/Claude.list,ai
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/gfw.txt,relay
DOMAIN-SET,https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/direct.txt,DIRECT
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT
FINAL,relay,dns-failed
